favicon: https://bananayx.github.io/files/img/Banana头像.png
banner: 'https://bananayx.github.io/files/img/Banana Y.X.导航白字小尺寸.png'

logo:
  expanded: 'https://bananayx.github.io/files/img/Banana Y.X.导航白字小尺寸.png'
  collapsed: https://bananayx.github.io/files/img/Banana头像.png
  dark: 'https://bananayx.github.io/files/img/Banana Y.X.导航黑字小尺寸.png'

flag:
  - name: Chinese
    default: true
    icon: flag-cn
    index: /index.html

search: true

userDefinedSearchData:
  custom: false
  thisSearch: https://cn.bing.com/search?q=
  thisSearchIcon: url(https://cn.bing.com/favicon.ico)
  hotStatus: true
  data:
    - name: 必应
      img: url(https://cn.bing.com/favicon.ico)
      url: https://cn.bing.com/search?q=

githubCorner: '<a href="https://github.com/Bananayx" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

expandAll: false
menu:
  - name: 有关Banana Y.X.
    config: aboutme
  - name: Banana Y.X.的资源分享
    config: myres
  - name: AI工具
    config: ai
    submenu:
      - name: AI对话
        config: ai-chat
      - name: AI声音
        config: ai-audio
      - name: AI图像
        config: ai-image
      - name: AI数据
        config: ai-data
      - name: AI开发
        config: ai-dev
      - name: AI工具集
        config: ai-tools
  - name: 游戏
    config: game
    submenu:
      - name: 在线游戏
        config: game-online
      - name: 游戏工具
        config: game-tool
      - name: 游戏资源
        config: game-res
      - name: 游戏教程
        config: game-tutorial
  - name: 下载
    config: download
    submenu:
      - name: 系统镜像
        config: download-system
      - name: 软件下载
        config: download-software
      - name: 资源下载
        config: download-resource
  - name: 网盘
    config: cloud
  - name: 工具
    config: tools
    submenu:
      - name: 临时邮件
        config: tools-email
      - name: 开发工具
        config: tools-dev
      - name: 在线工具
        config: tools-online

aboutme:
  - name: Banana Y.X.的小站
    url: https://bananayx.github.io/
    img: https://bananayx.github.io/files/img/Banana头像.png
    description: 小站，大世界。
  - name: Banana Y.X.网盘
    url: https://bananayx.github.io/pan
    img: https://bananayx.github.io/files/img/Banana头像.png
    description: 私人云存储，安全稳定高速。
  - name: 肿哥音乐
    url: https://bananayx.github.io/Solara-fork
    img: https://bananayx.github.io/files/img/Banana头像.png
    description: 肿哥音乐
  - name: Banana Y.X.的博客
    url: https://bananayx.github.io/blog
    img: https://bananayx.github.io/files/img/Banana头像.png
    description: 记录开发，分享知识。

myres:

ai-chat:
  - name: 豆包
    url: https://www.doubao.com/chat/
    img: https://lf-flow-web-cdn.doubao.com/obj/flow-doubao/doubao/chat/favicon.png
    description: 字节跳动旗下AI智能助手
  - name: DeepSeek
    url: https://chat.deepseek.com/
    img: https://fe-static.deepseek.com/chat/favicon.svg
    description: DeepSeek - 探索未至之境

ai-audio:
  - name: 悟声 AI
    url: https://www.wusound.cn/
    img: https://www.wusound.cn/favicon.ico
    description: 超拟真AI语音合成与瞬时克隆平台
  - name: TTSMaker
    url: https://ttsmaker.cn/
    img: https://ttsmaker.cn/favicon.ico
    description: 在线免费文字转语音
  - name: 音子AI
    url: https://yinziai.com/
    img: https://yinziai.com/favicon.ico
    description: 免费在线！Yinzi AI人声分离器
  - name: 音子AI
    url: https://www2.yinziai.com/
    img: https://www2.yinziai.com/favicon.ico
    description: 在线免费人声分离、伴奏分离器
  - name: LALAL.AI
    url: https://www.lalal.ai/zh-hans/
    img: https://www.lalal.ai/favicon.ico
    description: 人声去除器和AI智能伴奏分离器

ai-image:
  - name: remove.bg
    url: https://www.remove.bg/zh
    img: https://www.remove.bg/favicon.ico
    description: 在线抠图软件_图片去除背景
  - name: Magic Studio
    url: https://magicstudio.com/zh/
    img: https://magicstudio.com/favicon.ico
    description: 利用 AI 制作精美图像

ai-data:
  - name: ChatExcel
    url: https://chatexcel.com/#/
    img: https://chatexcel.com/logo.svg
    description: AI表格处理与数据分析

ai-dev:
  - name: Zread
    url: https://zread.ai/
    img: https://zread.ai/favicon.ico
    description: 专为开发者设计的AI源码解读产品

ai-tools:
  - name: AI工具集
    url: https://ai-bot.cn/
    img: https://ai-bot.cn/wp-content/uploads/2023/04/ai-bot-baidu-logo.png
    description: 700+ AI工具集合官网
  - name: EAST.IM
    url: https://east.im/zh
    img: https://east.im/favicon.ico
    description: 免费AI工具佼佼者

game-online:
  - name: 玩街机
    url: https://www.playfc.cn/arcades
    img: https://www.playfc.cn/favicon.ico
    description: 全网唯一可在线比拼分数的街机网站
  - name: Return8090
    url: https://www.return8090.com/
    img: https://www.return8090.com/favicon.ico
    description: 经典复古游戏机在线玩
  - name: 80在线街机游戏网
    url: https://wgame80.com/
    img: https://wgame80.com/favicon.ico
    description: 红白机，FC在线游戏，街机游戏
  - name: Poki (宝玩)
    url: https://poki.com/zh
    img: https://a.poki-cdn.com/icons/favicon-194x194.png
    description: 免费在线小游戏 - 马上玩！
  - name: Y8.com
    url: https://zh.y8.com/
    img: https://zh.y8.com/favicon.ico
    description: 免费线上游戏 - 立即在 Y8.com 上玩
  - name: Yandex游戏
    url: https://yandex.com/games/zh
    img: https://yandex.com/games/favicon.ico
    description: 适合各种口味的免费在线游戏
  - name: js13kGames
    url: https://js13kgames.com/
    img: https://bananayx.github.io/files/img/logo/js13kgames_f32.png
    description: HTML5 and JavaScript Game Development Competition
  - name: 局部战争Local War
    url: https://localwar.xidayun.com/
    img: https://bananayx.github.io/files/img/logo/FluentGlobe24Regular.svg
    description: 多人FPS射击页游
  - name: Subway Surfers
    url: https://subway-surfers.me/
    img: https://subway-surfers.me/favicon.ico
    description: Play Subway Surfers Online
  - name: 恐龙快打
    url: https://wgame80.com/game/26.html?title=%E6%81%90%E9%BE%99%E5%BF%AB%E6%89%93
    img: https://wgame80.com/favicon.ico
    description: 经典街机游戏恐龙快打
  - name: Oasis 2.0
    url: https://oasis2.decart.ai/demo
    img: https://oasis2.decart.ai/images/oasis2-logo-small.png
    description: AI生成的游戏世界

game-tool:
  - name: MCNav
    url: https://www.mcnav.net/
    img: https://www.mcnav.net/favicon.ico
    description: Minecraft网址导航站
  - name: Chunkbase
    url: https://www.chunkbase.com/apps/seed-map
    img: https://www.chunkbase.com/favicon.ico
    description: Minecraft种子地图查看器
  - name: 开服侠
    url: http://www.kaifuxia.com/
    img: http://www.kaifuxia.com/favicon.ico
    description: 我的世界开服侠 - 免费开服

game-res:
  - name: Koyso
    url: https://koyso.com/
    img: https://bananayx.github.io/files/img/logo/koyso.com-logo_u.ico
    description: PC Games Free Download
  - name: 快意库
    url: https://kooink.com/
    img: https://bananayx.github.io/files/img/logo/kooink.com-cropped-sitelogo-192x192.png
    description: 不止是艺术
  - name: 像素茶艺地图站
    url: https://pixelmap.minegraph.cn/
    img: https://pixelmap.minegraph.cn/wp-content/uploads/2024/02/cropped-image-6-192x192.png
    description: 我的世界地图下载
  - name: 搁浅资源网
    url: https://mcgeqian.top/
    img: https://mcgeqian.top/img/geqian.png
    description: Minecraft资源分享
  - name: open-source-games
    url: https://github.com/bobeff/open-source-games
    img: https://github.com/favicon.ico
    description: A list of open source games

game-tutorial:
  - name: 中文Minecraft Wiki
    url: https://zh.minecraft.wiki/
    img: https://zh.minecraft.wiki/images/Favicon.ico
    description: Minecraft教程

download-system:
  - name: WINOS
    url: https://www.winos.me/
    img: https://www.winos.me/favicon.ico
    description: 前沿的精简系统下载
  - name: HelloWindows
    url: https://hellowindows.cn/
    img: https://hellowindows.cn/logo-s.png
    description: Windows系统下载
  - name: ITELLYOU
    url: https://next.itellyou.cn/Original/
    img: https://next.itellyou.cn/favicon.ico
    description: MSDN原版系统下载
  - name: 我的MSDN
    url: https://www.imsdn.cn/
    img: https://www.imsdn.cn/favicon.ico
    description: MSDN原版系统,纯净镜像下载
  - name: MSDN, 我告诉你
    url: https://msdn.itellyou.cn/
    img: https://msdn.itellyou.cn/favicon.ico
    description: 做一个安静的工具站
  - name: UUP dump
    url: https://www.uupdump.cn/
    img: https://www.uupdump.cn/favicon.ico
    description: UUP dump不忘初心中文站
  - name: 小鱼儿yr系统
    url: https://www.yrxitong.com/h-nd-200.html
    img: https://www.yrxitong.com/favicon.ico
    description: 苹果电脑MacOS系统镜像
  - name: 蜂鸟PE
    url: https://www.fengpe.top/
    img: https://www.fengpe.top/favicon.ico
    description: 小而强悍的维护系统

download-software:
  - name: 4分贝分享网
    url: https://www.4fb.cn/
    img: https://www.4fb.cn/favicon.ico
    description: 软件分享网站
  - name: 鹿角软件
    url: https://lujiaorj.com/
    img: https://lujiaorj.com/img/logo.svg
    description: 专注分享实用软件
  - name: 拜拜软件
    url: https://www.88appp.com/
    img: https://bananayx.github.io/files/img/logo/88app.com-cropped-logo-xiao-1-192x192.webp
    description: 一个为软件而生的网站
  - name: 8号站
    url: https://www.ssdtop.com/
    img: https://www.ssdtop.com/favicon.ico
    description: 分享开源免费实用的软件
  - name: QiuQuan's Blog
    url: http://www.qiuquan.cc/
    img: http://www.qiuquan.cc/favicon.ico
    description: 精品软件分享博客
  - name: DOS之家
    url: http://www.doshome.com/
    img: http://www.doshome.com/favicon.ico
    description: 电脑安全的家
  - name: Microsoft Store - Generation Project
    url: https://store.rg-adguard.net/
    img: https://bananayx.github.io/files/img/logo/store.rg-adguard.net-favicon.ico
    description: Microsoft Store - Generation Project
  - name: 千千静听
    url: https://www.ttplayer.co/index.php
    img: https://www.ttplayer.co/favicon.ico
    description: 千千静听非官方网站
  - name: 喜马拉雅UWP版
    url: https://m.downxia.com/downinfo/383748.html
    img: https://m.downxia.com/favicon.ico
    description: 喜马拉雅FM微软商店版

download-resource:
  - name: Pixabay
    url: https://pixabay.com/zh/
    img: https://pixabay.com/favicon.ico
    description: 免费正版高清图片素材库
  - name: 100font
    url: https://www.100font.com/
    img: https://www.100font.com/view/img/favicon.ico
    description: 免费字体下载 - 免费商用字体下载网站
  - name: 我的世界字体包
    url: https://www.bilibili.com/opus/650428219754807321
    img: https://www.bilibili.com/favicon.ico
    description: 包含中英文的我的世界字体包
  - name: GitHub Proxy
    url: https://gh-proxy.com/
    img: https://gh-proxy.com/favicon.ico
    description: GitHub 文件加速代理
  - name: Github Proxy
    url: https://github.akams.cn/
    img: https://bananayx.github.io/files/img/logo/FluentGlobe24Regular.svg
    description: Github Proxy 文件代理加速
  - name: GetOneDriveDirectLink
    url: https://mapaler.github.io/GetOneDriveDirectLink/
    img: https://mapaler.github.io/GetOneDriveDirectLink/icon.png
    description: 获取OneDrive直链
  - name: SnapAny
    url: https://snapany.com/zh
    img: https://snapany.com/favicon.ico
    description: 万能视频图片解析下载
  - name: Windows 11 概念版光标
    url: https://www.softsy.cn/post-7.html
    img: https://www.softsy.cn/favicon.ico
    description: Windows 11 概念版光标 V2
  - name: Windows11手机壁纸
    url: https://zhutix.com/mobile/windows-11-wallpapers-for-your-phone/
    img: https://zhutix.com/favicon.ico
    description: Windows11手机壁纸

cloud:
  - name: 小莫云盘
    url: https://cloud.aoe.top/
    img: https://bananayx.github.io/files/img/logo/FluentGlobe24Regular.svg
  - name: 小太阳云盘
    url: https://cncncloud.com/
    img: https://cncncloud.com/static/img/favicon.ico
  - name: Meow云
    url: https://pan.miaogongzi.net/
    img: https://img.miaogongzi.org/2024/08/23/66c87cccb009d.png
  - name: huang1111网盘
    url: https://pan.huang1111.cn/
    img: https://a.h1static.cn/pan/Logohuang1111.ico
  - name: HotPan网盘
    url: https://pan.sysri.cn/
    img: https://sc.sysri.cn/i/p/1/65d45b2ce9c91.ico
  - name: 123云盘
    url: https://www.123pan.com/
    img: https://statics.123pan.com/static/pwa-icon-512.png
  - name: 钛盘
    url: https://www.tmp.link/
    img: https://www.ttttt.link/img/ico/favicon.ico
  - name: VIP优盘
    url: https://www.u-p.vip/
    img: https://web.u-p.vip/u-p/images/favicon.ico
  - name: 城通网盘
    url: https://www.ctfile.com/
    img: https://www.ctfile.com/favicon/apple-icon-180x180.png
  - name: 蓝奏云
    url: https://pc.woozooo.com/u
    img: https://pc.woozooo.com/favicon.ico
  - name: 阿里云盘
    url: https://www.alipan.com/
    img: https://www.alipan.com/favicon.ico
  - name: 扒拉云盘
    url: https://008686.xyz/
    img: https://008686.xyz/static/img/favicon.ico
  - name: 一刻相册
    url: https://photo.baidu.com/
    img: https://staticsns.cdn.bcebos.com/amis/2023-2/1676342310828/favicon.ico
    description: 百度网盘出品，无限空间云相册

tools-email:
  - name: Mail.tm
    url: https://mail.tm/zh/
    img: https://mail.tm/favicon.ico
    description: 临时邮件-一次性临时电子邮件服务
  - name: 10分钟邮箱
    url: https://tenminutesmail.net/zh
    img: https://tenminutesmail.net/uploads/favicon.ico
    description: 10 分钟邮箱 - 免费临时一次性邮箱
  - name: 临时邮箱
    url: https://www.linshi-email.com/
    img: https://www.linshi-email.com/favicon.ico
    description: 临时邮箱，10分钟邮箱

tools-dev:
  - name: GitHub Proxy
    url: https://gh-proxy.com/
    img: https://gh-proxy.com/favicon.ico
    description: GitHub 文件加速代理
  - name: Github Proxy
    url: https://github.akams.cn/
    img: https://bananayx.github.io/files/img/logo/FluentGlobe24Regular.svg
    description: Github Proxy 文件代理加速
  - name: GetOneDriveDirectLink
    url: https://mapaler.github.io/GetOneDriveDirectLink/
    img: https://mapaler.github.io/GetOneDriveDirectLink/icon.png
    description: 获取OneDrive直链

tools-online:
  - name: SnapAny
    url: https://snapany.com/zh
    img: https://snapany.com/favicon.ico
    description: 万能视频图片解析下载
  - name: remove.bg
    url: https://www.remove.bg/zh
    img: https://www.remove.bg/apple-touch-icon.png?v=fc0bfce6e1310f1539afec9729716721
    description: 在线抠图软件_图片去除背景
  - name: Magic Studio
    url: https://magicstudio.com/zh/
    img: https://magicstudio.com/favicon.ico
    description: 利用 AI 制作精美图像

since: 2025

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /nav/js/bootstrap.min.js
  TweenMax: /nav/js/TweenMax.min.js
  resizeable: /nav/js/resizeable.min.js
  joinable: /nav/js/joinable.js
  xenonApi: /nav/js/xenon-api.min.js
  xenonToggles: /nav/js/xenon-toggles.min.js
  xenonCustom: /nav/js/xenon-custom.min.js
  lozad: /nav/js/lozad.min.js
  html5shiv: /nav/js/html5shiv.min.js
  respond: /nav/js/respond.min.js
  busuanzi: https://cdn.busuanzi.cc/busuanzi/3.6.9/busuanzi.min.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
